In [2]:
# Square, symmetric, triangular, and diagonal matrices that are much as their names suggest.
# Identity matrices that are all zero values except along the main diagonal where the values are 1.
# Orthogonal matrices that generalize the idea of perpendicular vectors and have useful computational properties.

### Square matrix 
    A square matrix is a matrix where the number of rows (n) is equivalent to the number of columns (m).
    m = n
    [[1,2,3],
     [4,5,6],
     [7,8,9]]

### Symmetric matrix
    A symmetric matrix is a type of square matrix where the top-right triangle is the same as the bottom-left triangle
    [[1,2,3],
     [2,1,2],
     [3,2,1]]
    
    M = M^T

### Triangle matrix
    A triangular matrix is a type of square matrix that has all values in the upper-right or lower-left of the matrix with the remaining elements filled with zero values.
    [[1,2,3],
     [0,2,3],
     [0,0,3]]
     
     or
     
     [[1,0,0],
      [1,2,0],
      [1,2,3]]

In [4]:
import numpy as np

In [7]:
a = np.array([[1,2,3],
    [1,2,3],
    [1,2,3]])
# lower triangle matrix
lower = np.tril(a)
lower

array([[1, 0, 0],
       [1, 2, 0],
       [1, 2, 3]])

In [9]:
# upper triangle matrix
upper = np.triu(a)
upper

array([[1, 2, 3],
       [0, 2, 3],
       [0, 0, 3]])

### Diagonal matrix
    A diagonal matrix is one where values outside of the main diagonal have a zero value
    
    [[1,0,0],
     [0,2,0],
     [0,0,3]]


In [13]:
a = np.array([[1,2,3],
    [4,5,6],
    [7,8,9]])
diag = np.diag(a)
diag

array([1, 5, 9])

### Identity matrix
    An identity matrix is a square matrix that does not change a vector when multiplied.
    All of the scalar values along the main diagonal (top-left to bottom-right) have the value one, while all other values are zero.
    
    [[1,0,0],
     [0,1,0],
     [0,0,1]]

In [16]:
ident = np.identity(3)
ident

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Othogonal matrix
    Two vectors are orthogonal when their dot product equals zero.
    v.m = 0
    
    An Orthogonal matrix is often denoted as uppercase Q
    Q^T·Q = Q·Q^T =I

In [22]:
# define othogonal matrix
q = np.array([[1,0],
              [0,-1]])
# inverse equalence
v = np.linalg.inv(q)
v

array([[ 1.,  0.],
       [-0., -1.]])

In [25]:
# indentity equalence
ident = q.dot(q.T)
ident

array([[1, 0],
       [0, 1]])