In [2]:
import numpy as np

In [5]:
# Matrix addition C = A + B
a = np.array([[1,2,3],
             [4,5,6]])
b = np.array([[1,2,3],
             [4,5,6]])
c = a + b
c

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [7]:
# Matrix subtraction C = A - B
a = np.array([[1,2,3],
             [4,5,6]])
b = np.array([[1,2,3],
             [4,5,6]])
c = a - b
c

array([[0, 0, 0],
       [0, 0, 0]])

In [10]:
# Matrix multiplication C = A x B
a = np.array([[1,2,3],
             [4,5,6]])
b = np.array([[1,2,3],
             [4,5,6]])
c = a * b
c

array([[ 1,  4,  9],
       [16, 25, 36]])

In [12]:
# Matrix division C = A / B
a = np.array([[1,2,3],
             [4,5,6]])
b = np.array([[1,2,3],
             [4,5,6]])
c = a / b
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
# Matrix dot(multiplication) C = A - B
a = np.array([[1,2],
             [3,4],
             [5,6]])
b = np.array([[1,2],
             [3,4]])
c = a.dot(b)
c

array([[ 7, 10],
       [15, 22],
       [23, 34]])

In [16]:
# Matrix dot(multiplication) C = A - B
a = np.array([[1,2],
             [3,4],
             [5,6]])
b = np.array([[1,2],
             [3,4]])
c = a @ b
c

array([[ 7, 10],
       [15, 22],
       [23, 34]])