### Transpose
    A defined matrix can be transposed, which creates a new matrix with the number of columns and rows flipped

In [2]:
import numpy as np

In [5]:
a=np.array([[1,2,3],
          [4,5,6]])
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### Inverse
    Matrix inversion is a process that finds another matrix that when multiplied with the matrix, results in an identity matrix
    AB = BA = I

In [7]:
# invert matrix
a = np.array([[1,2],
              [3,4]])
b = np.linalg.inv(a)
b

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [10]:
np.round(a.dot(b),2)

array([[1., 0.],
       [0., 1.]])

### Trace
    A trace of a square matrix is the sum of the values on the main diagonal of the matrix (top-left to bottom-right)

In [12]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b = np.trace(a)
b

15

### Determinant
    The determinant of a square matrix is a scalar representation of the volume of the matrix
    The determinant describes the relative geometry of the vectors that make up the rows of the matrix
    More specifically, the determinant of a matrix A tells you the volume of a box with sides given by rows of A
    More technically, the determinant is the product of all the eigenvalues of the matrix
    det(A)
    
    The intuition for the determinant is that it describes the way a matrix will scale another matrix when they are multiplied together.

In [14]:
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
b = np.linalg.det(a)
b

-9.51619735392994e-16

### Rank
    The rank of a matrix is the estimate of the number of linearly independent rows or columns in a matrix
    An intuition for rank is to consider it the number of dimensions spanned by all of the vectors within a matrix
    
    For example, 
    a rank of 0 suggest all vectors span a point, 
    a rank of 1 suggests all vectors span a line, 
    a rank of 2 suggests all vectors span a two-dimensional plane.

In [23]:
# rank 0
a = np.array([[0,0],
             [0,0]])
b = np.linalg.matrix_rank(a)
b

0

In [26]:
# rank 1
a = np.array([[1,2],
             [1,2]])
b = np.linalg.matrix_rank(a)
b

1

In [28]:
# rank 2
a = np.array([[1,2],
             [3,4]])
b = np.linalg.matrix_rank(a)
b

2