In [2]:
import numpy as np

In [4]:
# Vector addition : c = a + b
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a + b
c

array([5, 7, 9])

In [6]:
# vector subtraction c = a - b
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a - b
c

array([-3, -3, -3])

In [8]:
# vector multification c = a x b
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a * b
c

array([ 4, 10, 18])

In [10]:
# vector division c = a / b
a = np.array([1,2,3])
b = np.array([4,5,6])
c = a / b
c

array([0.25, 0.4 , 0.5 ])

In [12]:
# vector dot c = a . b (a1 x b1 + a2 x b2 + a3 x b3)
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.dot(a, b)
c

32

In [13]:
# vector scaller multiplication c = s x v
a = np.array([1,2,3])
b = 0.5
c = a * b
c

array([0.5, 1. , 1.5])