In [2]:
import numpy as np

In [5]:
#Matrix

m = np.array([[1,5,6],
            [4,7,4],
            [2,0,9]])

In [7]:
m

array([[1, 5, 6],
       [4, 7, 4],
       [2, 0, 9]])

In [10]:
m.transpose()

array([[1, 4, 2],
       [5, 7, 0],
       [6, 4, 9]])

In [12]:
# Determinant
np.linalg.det(m)

-161.00000000000003

In [17]:
# Inverse (A^-1)
m_inv = np.linalg.inv(m)

In [19]:
# Identity matrix (result of matrix . inverse matrix)
iden_m = np.dot(m,m_inv)

In [22]:
iden_m = np.round(np.abs(iden_m), 0)

In [23]:
iden_m

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])