# Getting started with Data

In [1]:
import numpy as np
import pandas as pd
import json

## The world of Arrays with Numpy

Arrays are fundamental in processing data. Arrays are utilized to represent matrices which is heavily used in mathematics. Python by default comes with data structure like List which can be utilized for array operation but a python list on its own is not suitable to perform heavy mathematical operation as it is not optimized for it. 
Numpy is a wonderful python package by Travis Oliphant which has been created fundamentally for scientific computing. It helps in handling large  multi-dimensional arrays and matrices, along with a large library of high-level mathematical functions to operate on these arrays

### Creating an Array

In [2]:
n_array = np.array([[0, 1, 2, 3],
                 [4, 5, 6, 7],
                 [8, 9, 10, 11]])

The shape gives the size of each dimension of the array

In [3]:
n_array.shape

(3L, 4L)

The number of axes of the array

In [4]:
n_array.ndim

2

The number of elements

In [5]:
n_array.size

12

The datatype of the elements in the array

In [6]:
n_array.dtype.name

'int32'

### Mathematical Operations

When you have an array of data, you would like to perform certain mathematical operations on it. Below are few of the important ones

Subtracting two arrays

In [7]:
a = np.array([11, 12, 13, 14])
b = np.array([1, 2, 3, 4])
c = a - b
c


array([10, 10, 10, 10])

Squaring the array

In [8]:
b ** 2

array([ 1,  4,  9, 16])

Trignometric function on the array

In [10]:
np.cos(b)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

Conditional Operation

In [11]:
b < 2

array([ True, False, False, False], dtype=bool)

Matrix Multiplication - Element wise product and dot product

In [13]:
A1 = np.array([[1, 1],
            [0, 1]])

A2 = np.array([[2, 0],
            [3, 4]])

A1 * A2
np.dot(A1, A2)


array([[5, 4],
       [3, 4]])

### Indexes and slicing  Selecting a single element

In [13]:
n_array[0, 1]

1

select range of values in a row

In [14]:
n_array[0, 0:3]

array([0, 1, 2])

selecting an entire row of values

In [15]:
n_array[0, :]

array([0, 1, 2, 3])

selecting an entire column of values

In [17]:
n_array[:, 1]

array([1, 5, 9])

Changing the shape of the array

In [14]:
n_array.ravel()

n_array.shape = (6, 2)
n_array



array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [15]:
n_array.transpose()

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

## Empowering Data Analysis with Pandas

Pandas is an open source Python library specially designed for Data Analysis. It has been built on numpy and makes it easy to handle data. Numpy is a fairly low level tool which handles matrices really well and it can be seen similar to Matlab.
Pandas brings the richness of R in the world of python to handle the data. It’s got efficient data structures to process the data, performs fast joins, read data from various sources to name a few.

Pandas Data Structure

Pandas has essentially three data structures 
1. Series
2. Data Frame
3. Panel

### Series

Creating series from random numbers

In [17]:
pd.Series(np.random.randn(5))

0    1.098757
1    0.060494
2   -0.346703
3   -0.498025
4   -0.482826
dtype: float64

Creating series with row labels

In [18]:
pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])

a   -0.170402
b   -0.532428
c    0.823084
d   -0.027543
e    0.080242
dtype: float64

Creating series from dict

In [19]:
d = {'A': 10, 'B': 20, 'C': 30}  
pd.Series(d)

A    10
B    20
C    30
dtype: int64

### DataFrame

Creating data frame from a dict of Series

In [20]:
d = {'c1': pd.Series(['A', 'B', 'C']),
     'c2': pd.Series([1, 2., 3., 4.])}

df = pd.DataFrame(d)
df

c1  c2
0    A   1
1    B   2
2    C   3
3  NaN   4

Creating data frame from a dict of Lists

In [21]:
d = {'c1': ['A', 'B', 'C', 'D'],
     'c2': [1, 2., 3., 4.]}

df = pd.DataFrame(d)
df

c1  c2
0  A   1
1  B   2
2  C   3
3  D   4

### Panel

Creating a Panel Data

In [22]:
d = {'Item1': pd.DataFrame(np.random.randn(4, 3)),
     'Item2': pd.DataFrame(np.random.randn(4, 2))}

pd.Panel(d)

<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 4 (major_axis) x 3 (minor_axis)
Items axis: Item1 to Item2
Major_axis axis: 0 to 3
Minor_axis axis: 0 to 2

## Inputting and Exporting Data

The data is persisted in various forms like csv,tsv, databases etc. Pandas makes it convenient to read data from these formats or to export to these formats. We’ll use a dataset which contains the weight statistics of the school students from United states of America

### CSV

To read data from a csv file, the following command can be used

In [9]:
d = pd.read_csv('Data/Student_Weight_Status_Category_Reporting_Results__Beginning_2010.csv')
d[0:5]['AREA NAME']

0    RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT
1    RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT
2    RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT
3                        COHOES CITY SCHOOL DISTRICT
4                        COHOES CITY SCHOOL DISTRICT
Name: AREA NAME, dtype: object

 Writing data to a csv

In [23]:
d = {'c1': pd.Series(['A', 'B', 'C']),
     'c2': pd.Series([1, 2., 3., 4.])}

df = pd.DataFrame(d)
df.to_csv('sample_data.csv')

### Excel

 Reading data from an excel file

In [24]:
d = pd.read_excel('Data/Student_Weight_Status_Category_Reporting_Results__Beginning_2010.xls')
d[0:5]

LOCATION CODE  COUNTY                                        AREA NAME  \
0          10402  ALBANY  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT   
1          10402  ALBANY  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT   
2          10402  ALBANY  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT   
3          10500  ALBANY                      COHOES CITY SCHOOL DISTRICT   
4          10500  ALBANY                      COHOES CITY SCHOOL DISTRICT   

                  REGION SCHOOL YEARS  NO. OVERWEIGHT  PCT OVERWEIGHT  \
0  NORTHEASTERN NEW YORK    2012-2013             124           0.185   
1  NORTHEASTERN NEW YORK    2012-2013              74           0.192   
2  NORTHEASTERN NEW YORK    2012-2013              50           0.176   
3  NORTHEASTERN NEW YORK    2012-2013              84           0.172   
4  NORTHEASTERN NEW YORK    2012-2013              58           0.161   

   NO. OBESE  PCT OBESE  NO. OVERWEIGHT OR OBESE  PCT OVERWEIGHT OR OBESE  \
0        139      0.208                      263                    0.393   
1         72      0.187                      146                    0.379   
2         67      0.236                      117                    0.412   
3        124      0.254                      208                    0.425   
4         89      0.247                      147                    0.408   

      GRADE LEVEL        AREA TYPE  STREET ADDRESS    CITY STATE  ZIP CODE  \
0  DISTRICT TOTAL  SCHOOL DISTRICT  15 MOUNTAIN RD  RAVENA    NY     12143   
1      ELEMENTARY  SCHOOL DISTRICT  15 MOUNTAIN RD  RAVENA    NY     12143   
2     MIDDLE/HIGH  SCHOOL DISTRICT  15 MOUNTAIN RD  RAVENA    NY     12143   
3  DISTRICT TOTAL  SCHOOL DISTRICT      7 BEVAN ST  COHOES    NY     12047   
4      ELEMENTARY  SCHOOL DISTRICT      7 BEVAN ST  COHOES    NY     12047   

                                          Location 1  
0  15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...  
1  15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...  
2  15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...  
3  7 BEVAN ST\nCOHOES, NY 12047\n(42.771285452000...  
4  7 BEVAN ST\nCOHOES, NY 12047\n(42.771285452000...

Writing to Excel File

In [25]:
df.to_excel('sample_data.xls')

### JSON

Reading from json

In [26]:
json_data = open('Data/Student_Weight_Status_Category_Reporting_Results__Beginning_2010.json')
data = json.load(json_data)
json_data.close()

## Data Cleansing

### Handling missing data

checking if an instance is null

In [27]:
d = pd.read_csv('Data/Student_Weight_Status_Category_Reporting_Results__Beginning_2010.csv')
d['Location 1'].isnull()

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
        ...  
3240    False
3241    False
3242    False
3243    False
3244    False
3245    False
3246    False
3247    False
3248    False
3249    False
3250    False
3251    False
3252    False
3253    False
3254    False
3255    False
3256    False
3257    False
3258    False
3259    False
3260    False
3261    False
3262    False
3263    False
3264    False
3265    False
3266    False
3267     True
3268     True
3269     True
Name: Location 1, dtype: bool

Aggregating to count the null instances

In [28]:
d['Location 1'].isnull().value_counts()

False    3246
True       24
dtype: int64

removing the missing values

In [39]:
d['Location 1'].dropna()

0     15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...
1     15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...
2     15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...
3     7 BEVAN ST\nCOHOES, NY 12047\n(42.771285452000...
4     7 BEVAN ST\nCOHOES, NY 12047\n(42.771285452000...
5     7 BEVAN ST\nCOHOES, NY 12047\n(42.771285452000...
6     102 LORALEE DR\nALBANY, NY 12205\n(42.73352407...
7     102 LORALEE DR\nALBANY, NY 12205\n(42.73352407...
8     102 LORALEE DR\nALBANY, NY 12205\n(42.73352407...
9     91 FIDDLERS LN\nLATHAM, NY 12110\n(42.72935391...
10    91 FIDDLERS LN\nLATHAM, NY 12110\n(42.72935391...
11    91 FIDDLERS LN\nLATHAM, NY 12110\n(42.72935391...
12    171 HUDSON AVE\nGREEN ISLAND, NY 12183\n(42.74...
13    171 HUDSON AVE\nGREEN ISLAND, NY 12183\n(42.74...
14    171 HUDSON AVE\nGREEN ISLAND, NY 12183\n(42.74...
...
3252    (42.8213, -78.0944)
3253    (42.8213, -78.0944)
3254    (42.8213, -78.0944)
3255     (42.7236, -78.003)
3256     (42.7236, -78.003)
3257     (42.723

Removing all na instances

In [40]:
d = d.dropna(how='any')

### Filling the missing data

Let's create a dataframe with some values

In [32]:
df = pd.DataFrame(np.random.randn(5, 3), index=['a0', 'a10', 'a20', 'a30', 'a40'],
                  columns=['X', 'Y', 'Z'])
df

X         Y         Z
a0  -1.193371  0.912654 -0.780461
a10  1.413044  0.615997  0.947334
a20  1.583516  1.388921  0.458771
a30  0.479579  1.427625  1.407924
a40  0.455510 -0.880937  1.375555

Let's add some more values which will have null values

In [34]:
df2 = df.reindex(['a0', 'a1', 'a10', 'a11', 'a20', 'a21', 'a30', 'a31', 'a40','a41'])
df2

X         Y         Z
a0  -1.193371  0.912654 -0.780461
a1        NaN       NaN       NaN
a10  1.413044  0.615997  0.947334
a11       NaN       NaN       NaN
a20  1.583516  1.388921  0.458771
a21       NaN       NaN       NaN
a30  0.479579  1.427625  1.407924
a31       NaN       NaN       NaN
a40  0.455510 -0.880937  1.375555
a41       NaN       NaN       NaN

Filling with a zero value

In [36]:
df2.fillna(0)

X         Y         Z
a0  -1.193371  0.912654 -0.780461
a1   0.000000  0.000000  0.000000
a10  1.413044  0.615997  0.947334
a11  0.000000  0.000000  0.000000
a20  1.583516  1.388921  0.458771
a21  0.000000  0.000000  0.000000
a30  0.479579  1.427625  1.407924
a31  0.000000  0.000000  0.000000
a40  0.455510 -0.880937  1.375555
a41  0.000000  0.000000  0.000000

Filling with forward propagation

In [38]:
df2.fillna(method='pad')

X         Y         Z
a0  -1.193371  0.912654 -0.780461
a1  -1.193371  0.912654 -0.780461
a10  1.413044  0.615997  0.947334
a11  1.413044  0.615997  0.947334
a20  1.583516  1.388921  0.458771
a21  1.583516  1.388921  0.458771
a30  0.479579  1.427625  1.407924
a31  0.479579  1.427625  1.407924
a40  0.455510 -0.880937  1.375555
a41  0.455510 -0.880937  1.375555

Filling with the mean of the column

In [40]:
df2.fillna(df2.mean())

X         Y         Z
a0  -1.193371  0.912654 -0.780461
a1   0.547655  0.692852  0.681825
a10  1.413044  0.615997  0.947334
a11  0.547655  0.692852  0.681825
a20  1.583516  1.388921  0.458771
a21  0.547655  0.692852  0.681825
a30  0.479579  1.427625  1.407924
a31  0.547655  0.692852  0.681825
a40  0.455510 -0.880937  1.375555
a41  0.547655  0.692852  0.681825

## String Manipulation

There are character field columns which you would want to modify. The following techniques explains how to do it

### Substring

Choosing five rows of the Area column in the data

In [42]:
df = pd.read_csv('Data/Student_Weight_Status_Category_Reporting_Results__Beginning_2010.csv')
df['AREA NAME'][0:5]

0    RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT
1    RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT
2    RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT
3                        COHOES CITY SCHOOL DISTRICT
4                        COHOES CITY SCHOOL DISTRICT
Name: AREA NAME, dtype: object

In order to extract the 1st word from the Area Name column

In [19]:
df['AREA NAME'][0:5].str.extract('(\w+)')

0    RAVENA
1    RAVENA
2    RAVENA
3    COHOES
4    COHOES
Name: AREA NAME, dtype: object

Getting the 1st two words

In [44]:
df['AREA NAME'][0:5].str.extract('(\w+)\s(\w+)')

0         1
0  RAVENA  COEYMANS
1  RAVENA  COEYMANS
2  RAVENA  COEYMANS
3  COHOES      CITY
4  COHOES      CITY

### Uppercase

In [21]:
df['AREA NAME'][0:5].str.upper()

0    RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT
1    RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT
2    RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT
3                        COHOES CITY SCHOOL DISTRICT
4                        COHOES CITY SCHOOL DISTRICT
Name: AREA NAME, dtype: object

### Lowercase

In [22]:
df['AREA NAME'][0:5].str.lower()

0    ravena coeymans selkirk central school district
1    ravena coeymans selkirk central school district
2    ravena coeymans selkirk central school district
3                        cohoes city school district
4                        cohoes city school district
Name: AREA NAME, dtype: object

### Length

In [23]:
df['AREA NAME'][0:5].str.len()

0    47
1    47
2    47
3    27
4    27
Name: AREA NAME, dtype: int64

### Split

In [24]:
df['AREA NAME'][0:5].str.split(' ')

0    [RAVENA, COEYMANS, SELKIRK, CENTRAL, SCHOOL, D...
1    [RAVENA, COEYMANS, SELKIRK, CENTRAL, SCHOOL, D...
2    [RAVENA, COEYMANS, SELKIRK, CENTRAL, SCHOOL, D...
3                     [COHOES, CITY, SCHOOL, DISTRICT]
4                     [COHOES, CITY, SCHOOL, DISTRICT]
Name: AREA NAME, dtype: object

### Replace

To replace all the Area Names ending with DISTRICT to DIST

In [25]:
df['AREA NAME'][0:5].str.replace('DISTRICT$', 'DIST')

0    RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DIST
1    RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DIST
2    RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DIST
3                        COHOES CITY SCHOOL DIST
4                        COHOES CITY SCHOOL DIST
Name: AREA NAME, dtype: object

### Merging Data

To combine data sets together, the concat function of Pandas can be utilized.
Let’s take the Area Name and County with its first five rows

In [26]:
df[['AREA NAME', 'COUNTY']][0:5]

AREA NAME  COUNTY
0  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT  ALBANY
1  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT  ALBANY
2  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT  ALBANY
3                      COHOES CITY SCHOOL DISTRICT  ALBANY
4                      COHOES CITY SCHOOL DISTRICT  ALBANY

In [29]:
p1 = df[['AREA NAME', 'COUNTY']][0:2]
p2 = df[['AREA NAME', 'COUNTY']][2:5]

In [31]:
pd.concat([p1,p2])

AREA NAME  COUNTY
0  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT  ALBANY
1  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT  ALBANY
2  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT  ALBANY
3                      COHOES CITY SCHOOL DISTRICT  ALBANY
4                      COHOES CITY SCHOOL DISTRICT  ALBANY

The combined pieces can be identified by assigning a key

In [32]:
concatenated = pd.concat([p1,p2], keys = ['p1','p2'])
concatenated

AREA NAME  COUNTY
p1 0  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT  ALBANY
   1  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT  ALBANY
p2 2  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT  ALBANY
   3                      COHOES CITY SCHOOL DISTRICT  ALBANY
   4                      COHOES CITY SCHOOL DISTRICT  ALBANY

Using the keys, the pieces can be extracted back from concatenated data 

In [33]:
concatenated.ix['p1']

AREA NAME  COUNTY
0  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT  ALBANY
1  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT  ALBANY

## Aggregation Operations

There are number of aggregation operations like average, sum etc that you would like to do on a numerical field. Following explains on how to perform it 

### Average

To find out the average number of students in Elementary school who are Obese

In [38]:
data = df[df['GRADE LEVEL'] == 'ELEMENTARY']
data['NO. OBESE'].mean()

213.41593780369291

### SUM

To find out the total number of Elementary students who are obese across all the school

In [39]:
data['NO. OBESE'].sum()

219605.0

### MAX

To get the maximum number of students that are Obese in an elementary school

In [36]:
data['NO. OBESE'].max()

48843.0

### MIN

To get the minimum number of students that are Obese in an elementary school

In [40]:
data['NO. OBESE'].min()

5.0

### STD

To get the standard deviation of the number of Obese students

In [41]:
data['NO. OBESE'].std()

1690.3831128098113

### COUNT

To count the total number of schools with Elementary grade in the Columbia county

In [42]:
data = df[(df['GRADE LEVEL'] == 'ELEMENTARY') & (df['COUNTY'] == 'DELAWARE')]
data['COUNTY'].count()

19

## Joins

SQL like joins can be performed on the data frame using pandas.
Lets define a lookup dataframe which assigns levels to each of the grade

In [45]:
grade_lookup = {'GRADE LEVEL': pd.Series(['ELEMENTARY', 'MIDDLE/HIGH', 'MISC']),'LEVEL': pd.Series([1, 2, 3])}
grade_lookup = pd.DataFrame(grade_lookup)

Lets take the 1st five rows of the  grade data column as an example for performing the joins

In [44]:
df[['GRADE LEVEL']][0:5]

GRADE LEVEL
0  DISTRICT TOTAL
1      ELEMENTARY
2     MIDDLE/HIGH
3  DISTRICT TOTAL
4      ELEMENTARY

### Inner Join

An inner join can be performed with the following command

In [46]:
d_sub = df[0:5].join(grade_lookup.set_index(['GRADE LEVEL']), on=['GRADE LEVEL'], how='inner')
d_sub[['GRADE LEVEL', 'LEVEL']]

GRADE LEVEL  LEVEL
1   ELEMENTARY      1
4   ELEMENTARY      1
2  MIDDLE/HIGH      2

### Left Outer Join

A left outer join can be performed with the following commands

In [46]:
d_sub = df[0:5].join(grade_lookup.set_index(['GRADE LEVEL']), on=['GRADE LEVEL'], how='left')
d_sub[['GRADE LEVEL', 'LEVEL']]

GRADE LEVEL  LEVEL
0  DISTRICT TOTAL    NaN
1      ELEMENTARY      1
2     MIDDLE/HIGH      2
3  DISTRICT TOTAL    NaN
4      ELEMENTARY      1

### Full outer join

The full outer join can be performed with the following code

In [47]:
d_sub = df[0:5].join(grade_lookup.set_index(['GRADE LEVEL']), on=['GRADE LEVEL'], how='outer')
d_sub[['GRADE LEVEL', 'LEVEL']]

GRADE LEVEL  LEVEL
0  DISTRICT TOTAL    NaN
3  DISTRICT TOTAL    NaN
1      ELEMENTARY      1
4      ELEMENTARY      1
2     MIDDLE/HIGH      2
4            MISC      3

### Group By

Its easy to do an SQL like group by operation with Pandas. Lets say, if you want to find the sum of the number of Obese students in each of the grade then  you can use the following command

In [48]:
df['NO. OBESE'].groupby(d['GRADE LEVEL']).sum()

GRADE LEVEL
DISTRICT TOTAL    380851
ELEMENTARY        219605
MIDDLE/HIGH       160499
Name: NO. OBESE, dtype: float64

This command chooses the Number of Obese students column and then uses the  group by method to group the data based group level and finally the sum method sums up the number. The same can be achieved by the following function too

In [49]:
df['NO. OBESE'].groupby(d['GRADE LEVEL']).aggregate(sum)

GRADE LEVEL
DISTRICT TOTAL    380851
ELEMENTARY        219605
MIDDLE/HIGH       160499
Name: NO. OBESE, dtype: float64

Here the aggregate method is utilized. The sum function is passed to obtain the required results.
It’s also possible to obtain multiple kinds of aggregation on the same metric. This can be achieved by the following command

In [50]:
df['NO. OBESE'].groupby(d['GRADE LEVEL']).aggregate([sum, mean, std])

sum        mean          std
GRADE LEVEL                                    
DISTRICT TOTAL  380851  359.972590  2875.820653
ELEMENTARY      219605  213.415938  1690.383113
MIDDLE/HIGH     160499  162.943147  1252.104878